services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - plant-knowledge-assistant

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - plant-knowledge-assistant

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      DATA_PATH: "data/plants_data.csv"
      QDRANT_URL: ${QDRANT_URL}
    ports:
      - "${APP_PORT:-5000}:5000"
    depends_on:
      - postgres
      - qdrant
    networks:
      - plant-knowledge-assistant

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - postgres
    networks:
      - plant-knowledge-assistant

volumes:
  postgres_data:
  grafana_data:
  qdrant_storage:

networks:
  plant-knowledge-assistant:
    driver: bridge